// Run this once with: node download-poses.js
// Downloads all yoga pose images locally so the app works 100% offline during class.

import https from 'https';
import fs from 'fs';
import path from 'path';

const POSES_DIR = './src/poses';

if (!fs.existsSync(POSES_DIR)) {
  fs.mkdirSync(POSES_DIR, { recursive: true });
  console.log('📁 Created src/poses/ folder');
}

// Exact english_name matches from the API's 48 poses
const NEEDED_POSES = {
  breathwork:    'Corpse',
  figureFour:    'Pigeon',
  supineHipFlex: 'Butterfly',
  lowLunge:      'Low Lunge',
  pigeon:        'King Pigeon',
  seatedFold:    'Seated Forward Bend',
  legRaise:      'Extended Hand to Toe',
  calfStretch:   'Standing Forward Bend',
  sipBreak:      'Tree',
  threadNeedle:  'Wild Thing',
  childsPose:    "Child's Pose",
  chestOpener:   'Camel',
  crossBody:     'Eagle',
  thoracicExt:   'Cat',
  spinalTwist:   'Half Lord of the Fishes',
  catCow:        'Cow',
  happyBaby:     'Bridge',
  savasana:      'Corpse',
};

function fetchJSON(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch(e) { reject(e); }
      });
    }).on('error', reject);
  });
}

function downloadFile(url, dest) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(dest);
    https.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        file.close();
        fs.unlinkSync(dest);
        downloadFile(res.headers.location, dest).then(resolve).catch(reject);
        return;
      }
      res.pipe(file);
      file.on('finish', () => { file.close(); resolve(); });
    }).on('error', (err) => {
      try { fs.unlinkSync(dest); } catch(_) {}
      reject(err);
    });
  });
}

async function main() {
  console.log('🌐 Fetching pose list from API...\n');

  let poses;
  try {
    poses = await fetchJSON('https://yoga-api-nzy4.onrender.com/v1/poses');
    console.log(`✓ Got ${poses.length} poses\n`);
  } catch(e) {
    console.error('❌ Could not reach yoga API. Wait 60 seconds and try again.');
    process.exit(1);
  }

  // Build a lookup by exact english_name
  const byName = {};
  poses.forEach(p => { byName[p.english_name] = p; });

  const urlMap = {};
  const alreadyDownloaded = {}; // track by filename to avoid re-downloading same image twice

  for (const [key, poseName] of Object.entries(NEEDED_POSES)) {
    const match = byName[poseName];

    if (!match) {
      console.log(`⚠  No match for: ${key} → "${poseName}"`);
      continue;
    }

    const filename = `${key}.svg`;
    const dest = path.join(POSES_DIR, filename);

    // If we already downloaded this exact pose (e.g. breathwork + savasana both use Corpse)
    // just copy the file instead of downloading again
    const sourceKey = Object.keys(alreadyDownloaded).find(k => alreadyDownloaded[k] === poseName);
    if (sourceKey) {
      fs.copyFileSync(path.join(POSES_DIR, `${sourceKey}.svg`), dest);
      urlMap[key] = `./poses/${filename}`;
      console.log(`📋 ${key} (copied from ${sourceKey})`);
      continue;
    }

    process.stdout.write(`⬇  ${key} → ${poseName}... `);
    try {
      await downloadFile(match.url_svg, dest);
      urlMap[key] = `./poses/${filename}`;
      alreadyDownloaded[key] = poseName;
      console.log('✓');
    } catch(e) {
      console.log(`✗ (${e.message})`);
    }
  }

  // Write the import map for the React component
  const mapContent = `// Auto-generated by download-poses.js — do not edit manually
// Local image paths — no internet needed during class

const POSE_IMAGES = ${JSON.stringify(urlMap, null, 2)};

export default POSE_IMAGES;
`;

  fs.writeFileSync('./src/poseImages.js', mapContent);

  const count = Object.keys(urlMap).length;
  console.log(`\n✅ ${count}/18 poses saved to src/poses/`);
  console.log('✅ src/poseImages.js written\n');
  if (count < 18) console.log('⚠  Some poses missing — the app will show emoji fallbacks for those.\n');
  else console.log('🎉 All 18 poses ready. App is fully offline.\n');
}

main();
