// Auto-generated by download-poses.js — do not edit manually
// Local image paths — no internet needed during class

const POSE_IMAGES = {
  "breathwork": "/poses/savasana.png",
  "figureFour": "/poses/figureFour.png",
  "supineHipFlex": "/poses/supineHipFlex.png",
  "lowLunge": "/poses/lowLunge.png",
  "pigeon": "/poses/pigeon.png",
  "sideBend": "/poses/sideBend.png",
  "seatedFold": "/poses/seatedFold.png",
  "legRaise": "/poses/legRaise.png",
  "calfStretch": "/poses/calfStretch.png",
  "sipBreak": "/poses/sipBreak.png",
  "lyingQuad": "/poses/lyingQuad.png",
  "threadNeedle": "/poses/threadNeedle.png",
  "childsPose": "/poses/childsPose.png",
  "cobra": "/poses/cobra.png",
  "chestOpener": "/poses/chestOpener.png",
  "crossBody": "/poses/crossBody.png",
  "thoracicExt": "/poses/thoracicExt.png",
  "spinalTwist": "/poses/spinalTwist.png",
  "catCow": "/poses/catCow.png",
  "happyBaby": "/poses/happyBaby.png",
  "savasana": "/poses/savasana.png"
};

export default POSE_IMAGES;
